name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet on Linux
      run: dotnet build $GITHUB_WORKSPACE/**/*.sln --configuration Release
      if: (matrix.os != 'windows-latest')
    - name: Build with dotnet on Windows
      run: dotnet build $GITHUB_WORKSPACE\**\*.sln --configuration Release
      if: (matrix.os == 'windows-latest')
    - name: Test with dotnet on Linux
      run: dotnet test $GITHUB_WORKSPACE/**/*.sln
      if: (matrix.os != 'windows-latest')
    - name: Test with dotnet on Windows
      run: dotnet test $GITHUB_WORKSPACE\**\*.sln
      if: (matrix.os == 'windows-latest')
